---
- hosts: 192.168.239.141
  become: true
  become_user: root
  tasks:
   - name: Install FTP Server and enable service
     yum:
      pkg: vsftpd
      state: installed
   - name: Start FTP service
     service:
      name: vsftpd
      enabled: true
      state: started
###########################################
# Script Branch is second branch in this repository.
# You can out vsftp command in this file.
# What is ftp and sftp. What is the diffrence between ftp and sftp.
###############################################      
You are able to push data to remote repository.
Now you can check wheteher other side, means are you able to download update from remote repository to local system.

######################################################3
#This additing is done by Ansible test server 192.168.239.140
