---
- hosts: 192.168.239.141
  become: true
  become_user: root
  tasks:
   - name: Install FTP Server and enable service
     yum:
      pkg: vsftpd
      state: installed
   - name: Start FTP service
     service:
      name: vsftpd
      enabled: true
      state: started
###############################################
# This is commented lines to check git command.
# git init
# git clone "remote path of git repository"
# git branch "To check in which branch we are"
# git status
# git add "file name"
# git commit -m "commit message need to add while commiting to repository"
# git push origin master "here master is name of branch where we are adding modifications"
# #############################################W:      
